---
version: "3.8"
services:
  redis:
    image: redis:5
    ports:
      - 6379

  rabbitmq:
    image: rabbitmq:3.5-management
    environment:
      RABBITMQ_DEFAULT_USER: magento
      RABBITMQ_DEFAULT_PASS: magento
      RABBITMQ_DEFAULT_VHOST: magento
    ports:
      - 15672:15672
      - 5672:5672
      - 5671:5671

  elasticsearch:
    image: memoryleak/elasticsearch:7.6.2
    ports:
      - 6200
    volumes:
      - vol_local_mg23_elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025
      - 8025:8025

  php:
    image: memoryleak/php:7.3
    volumes:
      - vol_local_mg23_code:/var/www
    ports:
      - 9000
    depends_on:
      - mysql
      - elasticsearch
      - redis
      - rabbitmq

  php-composer:
    image: memoryleak/php:7.3-composer
    environment:
      COMPOSER_HOME: /root/.composer
    volumes:
      - vol_local_mg23_code:/var/www
      - ~/.config/composer:/root/.composer
    depends_on:
      - mysql
      - elasticsearch
      - redis
      - rabbitmq

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - vol_local_mg23_mysql:/var/lib/mysql

  nginx:
    image: memoryleak/nginx:alpine
    ports:
      - 8080:80
    volumes:
      - vol_local_mg23_code:/var/www
      - ./etc/magento.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  varnish:
    image: varnish:6.3.1
    ports:
      - 80:80
      - 6082
    tmpfs:
      - /var/lib/varnish:exec
    volumes:
      - ./etc/default.vcl:/etc/varnish/default.vcl
    depends_on:
      - nginx

volumes:
  vol_local_mg23_code:
    driver: local
  vol_local_mg23_mysql:
    driver: local
  vol_local_mg23_elasticsearch:
    driver: local
